version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      kube:
        patterns:
          - kube
          - k8s-openapi
      core:
        patterns:
          - serde
          - serde_*
          - serde-*
          - anyhow
          - thiserror
          - log
          - env_logger
          - syn
          - quote
          - heck
          - tokio
          - typed-builder
          - clap
          - clap-*
          - clap_*
          - schemars
      rest:
        patterns:
          - .*
