[package]
name = "version"
version = "1.5.0"
authors = ["Eirik Albrigtsen <sszynrae@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "version"
path = "version.rs"

[dependencies]
actix-rt = "1.1.0"
actix-web = "3.3.2"
actix-web-prom = "0.5.0"
futures = "0.3.8"
tokio = { version = "0.2.24", features = ["macros"] }
kube = "0.44.0"
kube-runtime = "0.44.0"
k8s-openapi = { version = "0.10.0", features = ["v1_19"], default-features=false }
serde = { version = "1.0.118", features = ["derive"] }
anyhow = "1.0.36"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
