[package]
name = "version"
version = "1.11.2"
authors = ["Eirik Albrigtsen <sszynrae@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[[bin]]
doc = false
name = "version"
path = "version.rs"

[dependencies]
axum = "0.4.5"
futures = "0.3.21"
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread", "signal"] }
k8s-openapi = { version = "0.14.0", features = ["v1_20"] }
serde = { version = "1.0.136", features = ["derive"] }
anyhow = "1.0.53"
tower-http = { version = "0.2.2", default-features = false, features = ["trace"] }
tracing = "0.1.30"
tracing-subscriber = "0.3.8"

[dependencies.kube]
version = "0.69.0"
features = ["runtime", "client"]

[features]
# local testing: ignore
#git = "https://github.com/kube-rs/kube-rs.git"
#rev = "08c894cef560bd716c10b9bba426b1355e1907fe"
#path = "../kube-rs/kube"
