[package]
name = "version"
version = "1.0.0"
authors = ["Eirik Albrigtsen <sszynrae@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "version"
path = "version.rs"

[dependencies]
actix-web = "1.0.5"
actix-web-prom = "0.1.2"
kube = { version = "0.12.0", features = ["openapi"] }
k8s-openapi = { version = "0.4.0", features = ["v1_13"] }
serde = "1.0.97"
serde_derive = "1.0.97"
actix = "0.8.3"
log = "0.4.7"
failure = "0.1.5"
env_logger = "0.6.2"
