[package]
name = "version"
version = "1.11.4"
authors = ["Eirik Albrigtsen <sszynrae@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[[bin]]
doc = false
name = "version"
path = "version.rs"

[dependencies]
axum = "0.5.0"
axum-extra = { version = "0.2.0", features = ["typed-routing"] }
futures = "0.3.21"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "signal"] }
k8s-openapi = { version = "0.14.0", features = ["v1_22"] }
serde = { version = "1.0.136", features = ["derive"] }
anyhow = "1.0.56"
tower-http = { version = "0.2.5", default-features = false, features = ["trace"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.9"

[dependencies.kube]
version = "0.70.0"
features = ["runtime", "client"]

[features]
# local testing: ignore
#git = "https://github.com/kube-rs/kube-rs.git"
#rev = "08c894cef560bd716c10b9bba426b1355e1907fe"
#path = "../kube-rs/kube"
