[package]
name = "version"
version = "1.11.0"
authors = ["Eirik Albrigtsen <sszynrae@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
publish = false

[[bin]]
doc = false
name = "version"
path = "version.rs"

[dependencies]
axum = "0.2.8"
futures = "0.3.17"
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread", "signal"] }
k8s-openapi = { version = "0.13.1", features = ["v1_20"], default-features = false }
serde = { version = "1.0.130", features = ["derive"] }
anyhow = "1.0.44"
tower-http = { version = "0.1.1", default-features = false, features = ["trace"] }
tracing = "0.1.29"
tracing-subscriber = "0.2.25"

[dependencies.kube]
version = "0.62.0"
features = ["runtime", "client"]
# local testing: ignore
#git = "https://github.com/kube-rs/kube-rs.git"
#rev = "08c894cef560bd716c10b9bba426b1355e1907fe"
#path = "../kube-rs/kube"
