[package]
name = "version"
version = "1.8.0"
authors = ["Eirik Albrigtsen <sszynrae@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
publish = false

[[bin]]
doc = false
name = "version"
path = "version.rs"

[dependencies]
actix-rt = "2.2.0"
actix-web = "4.0.0-beta.8"
actix-web-prom = "0.5.1"
futures = "0.3.15"
tokio = { version = "1.9.0", features = ["macros"] }
kube = "0.59.0"
kube-runtime = "0.59.0"
k8s-openapi = { version = "0.13.0", features = ["v1_20"], default-features=false }
serde = { version = "1.0.125", features = ["derive"] }
anyhow = "1.0.40"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
