[package]
name = "version"
version = "1.5.0"
authors = ["Eirik Albrigtsen <sszynrae@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "version"
path = "version.rs"

[dependencies]
actix-rt = "2.0.0-beta.2"
actix-web = "4.0.0-beta.1"
actix-web-prom = "0.5.1"
futures = "0.3.12"
tokio = { version = "1.2.0", features = ["macros"] }
kube = "0.50.0"
kube-runtime = "0.50.0"
k8s-openapi = { version = "0.11.0", features = ["v1_19"], default-features=false }
serde = { version = "1.0.119", features = ["derive"] }
anyhow = "1.0.38"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
