[package]
name = "version"
version = "1.3.0"
authors = ["Eirik Albrigtsen <sszynrae@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "version"
path = "version.rs"

[dependencies]
actix-rt = "1.1.0"
actix-web = "2.0.0"
actix-web-prom = "0.2.0"
futures = "0.3.5"
tokio = { version = "0.2.21", features = ["macros"] }
kube-runtime = { version = "0.37.0" }
kube = { version = "0.37.0" }
k8s-openapi = { version = "0.9.0", features = ["v1_17"], default-features=false }
serde = { version = "1.0.106", features = ["derive"] }
log = "0.4.11"
env_logger = "0.7.1"
anyhow = "1.0.31"
